travis:
  secure:
    BINSTAR_TOKEN: NvJj1Ij+TxsFoSXzGFTsfXhMvELlFQq143AfD+8rK4JJ5mP9FVNPrD1ubQh4O6iI2QMHf299z+lE2X2z3ktPpexYImvRkvrvpzfbUGoXClNCQqacJVs9ijwXJyk5FdIxx2eX3rL78/hChckFgAx8aQKc52ly0AHItuql14IDR0unEm0Zj4AS2Zlk4g/Qglzeyqy6P4sEdDYZLGLhtc1+Zi5XzcFU0uy/52Y/JbHLIsUh0jerEWxCEzzbyR1pRSwvsbX6tMprKCwdKYJBDCGz73KenprXZ0ys5HXX4LYTBEJW2CroO9ko0siSOaI/WC+zgisVGDKt+kyRCwrVAXVaUBdEUMelD8CoCMr9wv58lDYlSXWqJEXBhv2neJC9XIqM+/JePNTX86AdkEDuScF/+3CS3ZcT4A+lrP2sRaAsQ8k6BLSrJoesDv4++axwWSogyvODNDkyu66Y4ls3pH0eQ6197xYka615C+2VI2j+raeVSm10XwWEBJDVyRlpw7xcYWoiWb9iADrduyNGmiRKcqLAI3bMtj6VzJDAIJKKs/FuJz+NVRahokTTtFgKkr5TGKyyz84pchEL4IwHktsBQylmTWAoAaZfOprz8+rH62eZThB6wW0P5ziA/GgO8FSqNTB/gMjSDH/Le1pg+P2vuJZLGpsqoMK7chIQt+NO/zU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
