travis:
  secure:
    BINSTAR_TOKEN: ikn5iDCyGP4XL+hK4Qh5qpx7W7qKW6UayHYqJkpsPMIhxbZRpGhG+HuXGUOEV0Niv1cq7DQdYy8w6OvVZuvDQ2Q7YR4Fj3+MzLt7A/s/Es7IyHuRdVyXx+8W58NmsTjssbewlsC3PLGWegStU2fn/DEtJHjBLuz5O2AkrdngsRr5uwxf0nVP4W2QMdojBcIYqH3IBTRSketzvQ4dJfzh5lrBZMu63Dh6JxZyPG7nFlf2mgHfcoJcyxBlxnaXUqNS308CzHxwoWlXWTcVYyn9PjhaD7etM/UjIoQ7/fSNNmg0Boucc6PvTC/FjKgd21Lx95O1KH6J9bmcpYldsAMHN0sG0aYDnFtam1uG2H52ORJMlANzae+nka31KlQAZT43Pj+YOJjOJhDvETVHanO/1bN9vnG0/ajNzZb+DlwVRPtFX7zntiALINk5XkcPthe+mwBOR9i6j0HdvS8kPFtllm0tVjruNJRDuFcVzaRL/Gm8Wuw4P+A/c2D4KAtCk2wGdTwWbtdjYqHe4JuS1pJ0YcFL3iYwIM5Z62U275rCojAV0MhNwnpym/cZSzNLsFVpeU0mvwvte8+L9pFUukSvtZW/yXJAzVX3UdYGurMTds42mnCGBnBdrPJi86djDUoq8wdFCBcwKLHPAoXKbK8N2LbvXt5J2QgReiKqRd2Z/28=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
